-- Build runner: add runner_token to build_status so a self-hosted CI runner can
-- authenticate its build-result callback (POST /api/v1/github/builds/:id/report).
--
-- runner_token is a UUID generated by the server when a build is queued.
-- The runner receives it in the response body of the dispatch webhook and must
-- present it as a Bearer token when posting build results.  This prevents
-- unauthenticated external writes to build_status / game_artifacts.
--
-- Bucket D: actual cargo + wasm-bindgen execution runs on a self-hosted runner
-- (see scripts/run-wasm-build.sh).  This migration is the DB contract for that
-- runner integration.
ALTER TABLE build_status
    ADD COLUMN IF NOT EXISTS runner_token UUID;

-- Index to allow the runner-report handler to look up a build by token quickly.
CREATE INDEX IF NOT EXISTS idx_build_status_runner_token
    ON build_status(runner_token)
    WHERE runner_token IS NOT NULL;
