/**
 * CodeEditor — Monaco-backed in-browser code editor.
 *
 * Monaco is loaded lazily via dynamic import so it only appears in a separate
 * chunk and does not inflate the main bundle.  The `@monaco-editor/react`
 * package handles this automatically via its own loader.
 *
 * Props:
 *   value        string   — current source text
 *   onChange     fn       — called with new string on every change
 *   language     string   — Monaco language id (default: 'rust')
 *   theme        string   — Monaco theme (default: 'magnetite-dark')
 *   height       string   — CSS height (default: '420px')
 *   readOnly     bool     — disable editing (default: false)
 *   filename     string   — shown in the header bar (optional)
 *   className    string   — extra class on the wrapper (optional)
 */

import { lazy, Suspense, useCallback, useRef } from 'react';
import './CodeEditor.css';

// Lazy-load Monaco — this will be split into a separate chunk by Vite/Rollup.
const MonacoEditor = lazy(() => import('@monaco-editor/react'));

// ── Starter Rust source shown when no value is provided ──────────────────────

export const STARTER_RUST_SOURCE = `//! magnetite-game — starter game source
//! Generated by Magnetite Game Studio.
//!
//! Implement the \`AuthoritativeGame\` trait methods below.
//! Run locally with:  magnetite dev

use magnetite_runtime::prelude::*;
use serde::{Deserialize, Serialize};

/// Per-player state stored server-side.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct PlayerState {
    pub position: Vec2,
    pub health: u8,
    pub score: u32,
}

/// Shared world state broadcast to all clients each tick.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct WorldState {
    pub tick: u64,
    pub players: std::collections::HashMap<PlayerId, PlayerState>,
}

/// Client -> Server messages.
#[derive(Clone, Debug, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMsg {
    Move { dx: f32, dy: f32 },
    Action { kind: String },
}

/// Server -> Client messages.
#[derive(Clone, Debug, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMsg {
    StateSnapshot(WorldState),
    PlayerJoined { id: PlayerId },
    PlayerLeft   { id: PlayerId },
}

pub struct Game {
    world: WorldState,
}

#[async_trait::async_trait]
impl AuthoritativeGame for Game {
    type PlayerState = PlayerState;
    type WorldState  = WorldState;
    type ClientMsg   = ClientMsg;
    type ServerMsg   = ServerMsg;

    fn new() -> Self {
        Self { world: WorldState::default() }
    }

    async fn on_player_join(&mut self, id: PlayerId) -> Vec<(PlayerId, ServerMsg)> {
        self.world.players.insert(id, PlayerState::default());
        broadcast_all(&self.world, ServerMsg::PlayerJoined { id })
    }

    async fn on_player_leave(&mut self, id: PlayerId) -> Vec<(PlayerId, ServerMsg)> {
        self.world.players.remove(&id);
        broadcast_all(&self.world, ServerMsg::PlayerLeft { id })
    }

    async fn on_message(
        &mut self,
        from: PlayerId,
        msg: ClientMsg,
    ) -> Vec<(PlayerId, ServerMsg)> {
        match msg {
            ClientMsg::Move { dx, dy } => {
                if let Some(p) = self.world.players.get_mut(&from) {
                    p.position.x += dx;
                    p.position.y += dy;
                }
            }
            ClientMsg::Action { kind } => {
                log::debug!("action: {kind} from {from:?}");
            }
        }
        vec![]
    }

    async fn tick(&mut self) -> Vec<(PlayerId, ServerMsg)> {
        self.world.tick += 1;
        broadcast_all(&self.world, ServerMsg::StateSnapshot(self.world.clone()))
    }
}

/// Helper: broadcast a message to every connected player.
fn broadcast_all(world: &WorldState, msg: ServerMsg) -> Vec<(PlayerId, ServerMsg)> {
    world.players.keys().map(|id| (*id, msg.clone())).collect()
}
`;

// ── Monaco editor options ────────────────────────────────────────────────────

function buildEditorOptions(readOnly) {
  return {
    readOnly,
    minimap: { enabled: false },
    scrollBeyondLastLine: false,
    fontSize: 13,
    fontFamily: "'JetBrains Mono', ui-monospace, 'Cascadia Code', 'Fira Code', Consolas, monospace",
    fontLigatures: true,
    lineHeight: 22,
    padding: { top: 16, bottom: 16 },
    renderLineHighlight: 'gutter',
    smoothScrolling: true,
    cursorBlinking: 'smooth',
    cursorSmoothCaretAnimation: 'on',
    bracketPairColorization: { enabled: true },
    formatOnPaste: true,
    tabSize: 4,
    wordWrap: 'off',
    scrollbar: {
      verticalScrollbarSize: 6,
      horizontalScrollbarSize: 6,
      useShadows: false,
    },
    overviewRulerLanes: 0,
    hideCursorInOverviewRuler: true,
    glyphMargin: false,
    lineNumbersMinChars: 3,
    folding: true,
    foldingHighlight: false,
  };
}

// ── Custom theme definition ──────────────────────────────────────────────────

function defineTheme(monaco) {
  monaco.editor.defineTheme('magnetite-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      // Rust keyword / type highlights tuned to Magnetite teal/amber palette
      { token: 'keyword',          foreground: '38e1c8', fontStyle: 'bold' },
      { token: 'keyword.control',  foreground: '5b9dff' },
      { token: 'type',             foreground: 'f5a524' },
      { token: 'type.identifier',  foreground: 'f5a524' },
      { token: 'string',           foreground: '3ddc84' },
      { token: 'string.escape',    foreground: '3ddc84', fontStyle: 'bold' },
      { token: 'number',           foreground: 'f5a524' },
      { token: 'comment',          foreground: '4a4a5a', fontStyle: 'italic' },
      { token: 'comment.doc',      foreground: '5b6b7a', fontStyle: 'italic' },
      { token: 'delimiter',        foreground: '6b7b8a' },
      { token: 'attribute',        foreground: 'a8b8c8' },
      { token: 'macro',            foreground: '38e1c8' },
      { token: 'function',         foreground: 'c8d8e8' },
      { token: 'variable',         foreground: 'e0e0ee' },
      { token: 'constant',         foreground: 'f5a524', fontStyle: 'bold' },
      { token: 'lifetime',         foreground: 'ff9055', fontStyle: 'italic' },
    ],
    colors: {
      'editor.background':            '#07070b',
      'editor.foreground':            '#f4f4f6',
      'editor.lineHighlightBackground':'#14141d',
      'editor.selectionBackground':   '#38e1c822',
      'editor.findMatchBackground':   '#f5a52440',
      'editor.findMatchHighlightBackground': '#f5a52420',
      'editorLineNumber.foreground':  '#3b3b4a',
      'editorLineNumber.activeForeground': '#6b6b78',
      'editorGutter.background':      '#07070b',
      'editorCursor.foreground':      '#38e1c8',
      'editorWhitespace.foreground':  '#1e1e2a',
      'editorIndentGuide.background': '#1b1b27',
      'editorBracketMatch.background':'#38e1c815',
      'editorBracketMatch.border':    '#38e1c8',
      'scrollbarSlider.background':   '#23232e',
      'scrollbarSlider.hoverBackground': '#33333f',
      'scrollbarSlider.activeBackground': '#38e1c840',
      'statusBar.background':         '#0f0f16',
      'statusBar.foreground':         '#6b6b78',
      'editorWidget.background':      '#14141d',
      'editorWidget.border':          '#23232e',
      'input.background':             '#0f0f16',
      'input.border':                 '#23232e',
      'input.foreground':             '#f4f4f6',
      'inputOption.activeBorder':     '#38e1c8',
      'list.hoverBackground':         '#14141d',
      'list.activeSelectionBackground': '#1b1b27',
      'dropdown.background':          '#14141d',
      'dropdown.border':              '#23232e',
    },
  });
}

// ── Fallback while Monaco loads ───────────────────────────────────────────────

function EditorSkeleton({ height }) {
  return (
    <div
      className="ce-skeleton"
      style={{ height }}
      aria-label="Loading code editor…"
      aria-busy="true"
    >
      {/* Fake gutter + line shimmer rows */}
      {Array.from({ length: 8 }, (_, i) => (
        <div key={i} className="ce-skeleton-row" style={{ animationDelay: `${i * 60}ms` }}>
          <span className="ce-skeleton-ln" />
          <span className="ce-skeleton-code" style={{ width: `${45 + (i * 17) % 42}%` }} />
        </div>
      ))}
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function CodeEditor({
  value = STARTER_RUST_SOURCE,
  onChange,
  language = 'rust',
  theme = 'magnetite-dark',
  height = '420px',
  readOnly = false,
  filename,
  className = '',
}) {
  const editorRef = useRef(null);

  const handleMount = useCallback((editor, monaco) => {
    editorRef.current = editor;
    // Define and apply our custom theme
    defineTheme(monaco);
    monaco.editor.setTheme(theme);
    // Give focus for immediate keyboard use
    editor.focus();
  }, [theme]);

  const handleChange = useCallback((val) => {
    if (onChange) onChange(val ?? '');
  }, [onChange]);

  return (
    <div className={`ce-root ${className}`.trim()}>
      {/* Header bar */}
      <div className="ce-header" aria-hidden="true">
        <div className="ce-dots">
          <span className="ce-dot ce-dot--red" />
          <span className="ce-dot ce-dot--amber" />
          <span className="ce-dot ce-dot--green" />
        </div>
        {filename && (
          <span className="ce-filename">{filename}</span>
        )}
        <div className="ce-lang-badge">{language}</div>
      </div>

      {/* Editor viewport */}
      <div className="ce-viewport">
        <Suspense fallback={<EditorSkeleton height={height} />}>
          <MonacoEditor
            height={height}
            language={language}
            value={value}
            theme={theme}
            options={buildEditorOptions(readOnly)}
            onMount={handleMount}
            onChange={handleChange}
            loading={<EditorSkeleton height={height} />}
          />
        </Suspense>
      </div>
    </div>
  );
}
