//! The embedded 2048-word key-name wordlist.
//!
//! # Provenance and licence
//!
//! Derived mechanically from `/usr/share/dict/words` on macOS, which is the
//! **Webster's Second International** ("web2") word list as distributed with
//! BSD systems. That file is in the **public domain** (it is the 1934 Webster's
//! Second, whose copyright expired; FreeBSD ships it with no licence
//! restrictions). No BIP-39 list is vendored here, so no Bitcoin-project
//! licensing question arises.
//!
//! # Derivation rule (reproducible)
//!
//! 1. Keep every line matching `^[a-z]{4,7}$` (ASCII lowercase, 4–7 letters —
//!    no proper nouns, no apostrophes, no hyphens).
//! 2. Walking the file in order, keep a word only if its **first four
//!    characters** have not been seen. This guarantees every entry has a unique
//!    4-character prefix, so names stay unambiguous under typo-tolerant prefix
//!    matching and no two words can be confused by their opening.
//! 3. Sort and de-duplicate → 15 491 candidates.
//! 4. Select 2048 of them evenly spaced: `candidates[i * 15491 / 2048]` for
//!    `i` in `0..2048`, so the list spans the whole alphabet rather than
//!    clustering in `a`–`c`.
//!
//! The invariants (length, sortedness, uniqueness, unique 4-prefixes, charset)
//! are asserted by tests in the parent module, so a corrupted list fails CI
//! rather than silently changing every name.

/// 2048 words — exactly 11 bits of information per word.
pub static WORDLIST: [&str; 2048] = [
    "aalii", "abate", "abdest", "abet", "abilao", "abjudge", "abmho", "aboma",
    "abrico", "abstain", "abura", "academe", "acaudal", "acedia", "achieve", "aciform",
    "acloud", "acock", "acouasm", "acta", "aculea", "acystia", "adat", "adda",
    "adeling", "adhere", "adipate", "adless", "adonin", "adpao", "adsbud", "advene",
    "aedile", "aerage", "afar", "afflict", "aflame", "afoul", "aftward", "agate",
    "ageusia", "agist", "agnail", "agon", "agroan", "agynary", "ahimsa", "ahull",
    "aide", "ailing", "aimful", "aint", "airily", "airy", "ajangle", "akala",
    "akee", "akhyana", "akonge", "alaihi", "alba", "alco", "alec", "alerce",
    "alfet", "algum", "alight", "aliquot", "alkali", "allege", "allude", "almuce",
    "alod", "alop", "alpieu", "altaite", "aludel", "alveary", "amadou", "amapa",
    "amble", "amelia", "amiable", "amiss", "ammine", "amok", "ampalea", "amreeta",
    "amula", "amyelia", "anadem", "anaqua", "anbury", "anele", "angaria", "anguid",
    "anima", "ankle", "anoa", "anopia", "answer", "antoeci", "anus", "aonach",
    "apagoge", "apedom", "apex", "apian", "apish", "apod", "apoop", "appall",
    "apron", "apulse", "araca", "arar", "arcing", "ardri", "arena", "argue",
    "ariel", "arkite", "armhole", "army", "arock", "arow", "arsheen", "artful",
    "arumin", "arzun", "asbolin", "ascribe", "asexual", "ashore", "aside", "askip",
    "asmear", "asop", "asport", "asslike", "astilbe", "asweat", "atangle", "atbash",
    "athanor", "athymia", "atloid", "atom", "atrocha", "atule", "atypic", "aucuba",
    "auhuhu", "aumaga", "aune", "auryl", "aute", "avadana", "avellan", "avijja",
    "avolate", "awag", "awat", "aweigh", "awin", "awnless", "awry", "axiform",
    "axmaker", "axunge", "ayless", "azide", "azole", "azulene", "babbitt", "baby",
    "bacula", "badness", "baggage", "bagwig", "baignet", "baize", "bakli", "bali",
    "baltei", "bane", "banshee", "barb", "barm", "baru", "basial", "batch",
    "bats", "baud", "bavoso", "baxter", "baylet", "bazzite", "beam", "bebeast",
    "becense", "bedad", "bedight", "bedtick", "beehead", "bees", "befret", "begnaw",
    "behold", "beisa", "bela", "bell", "bemeal", "bene", "bensel", "bepiece",
    "berhyme", "berth", "beshade", "besra", "betoil", "bevined", "bework", "bezel",
    "bhara", "bhungi", "biaxal", "bichir", "bidder", "bietle", "bifront", "bigroot",
    "bilabe", "bill", "bimodal", "binna", "biome", "bipack", "bireme", "birse",
    "bison", "bite", "biune", "bizet", "blaff", "blat", "bleb", "blesbok",
    "blind", "blodite", "blot", "bluing", "boast", "bobo", "bock", "bodkin",
    "bogie", "bogy", "boist", "bole", "bolus", "bonfire", "bonxie", "boojum",
    "boose", "bore", "borsch", "bosh", "botch", "bouchal", "bouse", "bowback",
    "bowpin", "boxfish", "boyang", "boza", "brag", "bravade", "breccia", "breme",
    "briar", "brin", "brocade", "bronc", "brugh", "brut", "bubo", "bucrane",
    "budzat", "bugdom", "buhl", "bulb", "bulse", "bumwood", "bunnell", "burfish",
    "burn", "bury", "bust", "butment", "buzane", "bygane", "byplay", "byspell",
    "caba", "cabree", "cacti", "cadjan", "caeca", "cage", "caid", "cajole",
    "calean", "caltrap", "camilla", "canaba", "canjac", "cant", "cape", "capomo",
    "carcake", "carl", "cart", "cash", "catalpa", "cation", "catskin", "cauk",
    "cautel", "cawney", "cearin", "cedar", "celemin", "cenacle", "cephid", "ceria",
    "ceryl", "cevine", "chagan", "chao", "chaw", "chef", "cheque", "chia",
    "chikara", "chit", "choel", "chondre", "choya", "chufa", "church", "cibol",
    "cilia", "cingle", "cipo", "cise", "citole", "cixiid", "clan", "claw",
    "clem", "cleve", "clip", "clochan", "clop", "club", "clutch", "coabode",
    "coannex", "cobcab", "cobra", "coctile", "codger", "coed", "coeval", "cognac",
    "coho", "coital", "cole", "colt", "comic", "cond", "conoid", "cony",
    "cool", "cope", "copula", "corf", "corp", "coscet", "cosy", "cotrine",
    "coude", "courage", "cowal", "cowish", "cowy", "coyish", "cozy", "crake",
    "craunch", "cree", "crevice", "crin", "croft", "crotal", "crude", "crural",
    "crypt", "cubbing", "cudava", "cueist", "cuke", "culotte", "cumic", "cunila",
    "cupel", "cuprene", "cure", "curt", "cusk", "cutheal", "cuvette", "cyesis",
    "cymoid", "cyrus", "dabb", "dacoit", "daemon", "daghesh", "daimen", "dalar",
    "dambose", "danaid", "danner", "darbha", "darn", "dasnt", "dattock", "dauw",
    "dawkin", "dayfly", "dazy", "dean", "debile", "deciare", "dedo", "defease",
    "defy", "dehair", "deink", "delf", "demagog", "dene", "deny", "deplane",
    "derby", "dertrum", "deslime", "detach", "deuton", "dewbeam", "dewret", "dhai",
    "dhaw", "dhow", "diaene", "diatom", "dibrach", "dicta", "didst", "diene",
    "digger", "digs", "dildo", "dime", "dinder", "dinsome", "diol", "diphase",
    "dipware", "dirndl", "disfame", "disobey", "disyoke", "diva", "dixy", "djerib",
    "dobson", "dodd", "doebird", "dogcart", "dogma", "doina", "dole", "domba",
    "donable", "dont", "dool", "doree", "dorp", "doss", "doty", "doup",
    "dowd", "dowry", "drab", "drang", "drazel", "drias", "drip", "drome",
    "drow", "drung", "drying", "dubash", "duchess", "dudine", "dufoil", "duhat",
    "dulbert", "dult", "dumsola", "dung", "duodena", "duppy", "durn", "dush",
    "dutra", "dwang", "dyce", "dynamic", "dzeren", "earcap", "earn", "easier",
    "ebbman", "ecanda", "echidna", "eclogue", "ectad", "edaphic", "edema", "edict",
    "eeler", "effable", "egad", "egghead", "egohood", "ehlite", "eisodic", "ekka",
    "elbow", "elegant", "elfland", "elkhorn", "ellops", "else", "elvan", "embed",
    "emeer", "emir", "empall", "emulant", "enapt", "encina", "endgate", "endyma",
    "enfoil", "engrace", "enjail", "enmask", "ennui", "enough", "enruin", "ensmall",
    "entach", "envapor", "enwrap", "eoside", "epee", "epibole", "epinaos", "epoch",
    "equable", "erase", "erethic", "eristic", "erogeny", "erth", "eschar", "esne",
    "espy", "estival", "etamine", "ethnal", "etude", "euclase", "eunomy", "eupione",
    "eustyle", "evangel", "evetide", "evitate", "evzone", "excamb", "exdie", "exes",
    "exigent", "exomion", "expiate", "exsect", "extund", "eyeball", "eyepit", "eyot",
    "fabular", "facy", "faff", "faience", "fakir", "falutin", "fana", "fanlike",
    "farad", "farm", "fass", "fatless", "fauld", "favn", "feal", "feces",
    "feel", "feil", "felucca", "fence", "fensive", "feria", "fertile", "fetial",
    "feud", "fezzed", "fiber", "fickle", "fiducia", "fifie", "figless", "filbert",
    "filter", "fingent", "fipenny", "firm", "fish", "fitness", "fixed", "flaccid",
    "flap", "flay", "flerry", "flick", "flirt", "floc", "flora", "flucan",
    "flurn", "flyflap", "flyway", "fodda", "foeman", "fogman", "foil", "folles",
    "fons", "fopling", "forfar", "fornent", "fosie", "foud", "foussa", "foxer",
    "foxy", "fraghan", "fraud", "freight", "fried", "frit", "froise", "frough",
    "frutify", "fucoid", "fugal", "fulcral", "fulth", "fume", "funk", "furdel",
    "further", "fusoid", "futile", "fylfot", "gaby", "gadman", "gaet", "gahnite",
    "gala", "galp", "gamma", "gander", "ganza", "gapy", "garial", "garten",
    "gasless", "gather", "gaufer", "gaut", "gawby", "gaycat", "gaze", "geat",
    "gedrite", "geet", "geld", "gemless", "gene", "genys", "geonoma", "gerefa",
    "gervao", "getter", "ghaist", "gheleem", "ghrush", "gibleh", "gigback", "gigsman",
    "gilo", "gimmal", "gipper", "giro", "gitalin", "glace", "glashan", "gleg",
    "glime", "glochid", "gloss", "glucase", "glut", "gnat", "goal", "goblet",
    "godkin", "goel", "going", "golland", "gonad", "goober", "goose", "gorge",
    "gory", "gotch", "goujon", "gowan", "goyim", "graham", "grat", "grece",
    "grey", "grike", "grizzle", "grommet", "grozart", "grum", "guacimo", "guasa",
    "guddle", "guerdon", "gugu", "guinea", "gule", "gumbo", "guna", "gunj",
    "gunsel", "gurjun", "gusla", "guyer", "gwyniad", "gype", "gyte", "habnab",
    "hade", "haff", "hagfish", "haik", "hakdar", "hale", "halurgy", "hami",
    "hanaper", "hanna", "hapten", "haricot", "hart", "hassar", "hatless", "hause",
    "hawer", "hayey", "hayward", "head", "heave", "hedge", "hegari", "heii",
    "helder", "helve", "henad", "henna", "hepcat", "herl", "hertz", "heuau",
    "hewn", "hiant", "hidden", "higgle", "hill", "hinch", "hipe", "hirable",
    "hisn", "hitter", "hoblike", "hodful", "hogfish", "hogward", "hokey", "holm",
    "homily", "honied", "hoof", "hopbine", "hopvine", "horse", "hotbed", "hotness",
    "houtou", "howff", "huaca", "hued", "huia", "hulsite", "humhum", "hundi",
    "hure", "husband", "husting", "huzz", "hyena", "hyle", "hypate", "hyraces",
    "ibid", "iced", "ichthus", "icotype", "ideist", "idle", "idryl", "iguana",
    "ikey", "ilex", "illeck", "ilot", "imbondo", "immense", "impi", "imshi",
    "inarch", "inbread", "incog", "indraft", "inesite", "infra", "ingraft", "initial",
    "inkish", "inky", "inmeats", "inogen", "inphase", "insack", "install", "into",
    "invade", "inwood", "ionogen", "iracund", "irid", "isagoge", "isidium", "isobar",
    "isomer", "isthmi", "itcze", "itzebu", "ixodian", "jabers", "jack", "jady",
    "jagrata", "jalkar", "jampan", "jantu", "jara", "jarra", "jati", "jawab",
    "jaypie", "jeel", "jelick", "jerboa", "jersey", "jetsam", "jharal", "jibi",
    "jigman", "jimmy", "jinx", "jitter", "jobman", "joewood", "joke", "joom",
    "joskin", "jouk", "jowel", "joyleaf", "juck", "jugal", "juju", "jumelle",
    "junk", "juridic", "juvenal", "kachin", "kago", "kainga", "kaki", "kamahi",
    "kande", "kaolin", "karch", "kartel", "kassu", "katogle", "kayak", "kebab",
    "keek", "keffel", "kele", "kemp", "keno", "kerel", "kerugma", "keto",
    "kewpie", "khaddar", "khar", "khir", "kiack", "kibitka", "kidnap", "kike",
    "kill", "kimono", "kinless", "kipe", "kirombo", "kiss", "kitish", "kiyi",
    "klip", "knag", "knet", "knit", "knout", "koae", "koel", "koine",
    "kola", "kombu", "kooka", "kora", "kosher", "kotyle", "kozo", "kras",
    "krimmer", "kuan", "kuei", "kulm", "kung", "kuruma", "kuttab", "kwazoku",
    "kyrine", "lablab", "lack", "lacy", "ladle", "lagna", "laiose", "lall",
    "lamnid", "lank", "lapacho", "lapse", "larmier", "lascar", "latch", "latus",
    "lave", "lawman", "laxism", "layman", "lazule", "leam", "leawill", "lede",
    "leer", "legged", "legua", "lemel", "lend", "lent", "lepra", "less",
    "letup", "levo", "leyland", "libel", "licit", "lied", "lieve", "ligula",
    "lile", "lime", "limy", "linie", "linwood", "lipoid", "lish", "litch",
    "lituite", "lixive", "load", "lobcock", "lobular", "lode", "loge", "logway",
    "loka", "lomita", "look", "lophiid", "lori", "lory", "lote", "loud",
    "lour", "lowbell", "lowth", "lube", "lucre", "lufbery", "luhinga", "luminal",
    "lunoid", "lura", "lush", "luthern", "lyard", "lyery", "lyric", "lyxose",
    "machan", "madcap", "madnep", "maffia", "magi", "mahmal", "maiid", "majesty",
    "makuk", "mall", "mana", "manhead", "manred", "maomao", "marble", "mark",
    "marsh", "mash", "mast", "matless", "matzo", "maux", "maycock", "maysin",
    "mazzard", "meal", "media", "meek", "megohm", "meith", "melt", "meng",
    "menu", "meriah", "mesa", "mess", "metra", "mewl", "miaul", "miction",
    "midpit", "mien", "mikado", "milfoil", "milreis", "mimic", "mind", "minster",
    "mirbane", "miry", "misfare", "misobey", "misyoke", "mixable", "mneme", "mobcap",
    "mocuck", "moff", "moho", "moio", "moko", "molimen", "mombin", "monial",
    "mood", "mopane", "mopus", "morkin", "morsal", "mosque", "motor", "moujik",
    "movable", "mowha", "moyen", "mubarat", "mucro", "mudhead", "muezzin", "muid",
    "mulder", "mult", "mung", "murder", "murphy", "muse", "muss", "mutsje",
    "myatony", "myiosis", "myology", "myoxine", "mysoid", "naam", "nacarat", "naegate",
    "nagnag", "naik", "naither", "name", "nanga", "naos", "napron", "nark",
    "nasi", "nathe", "naunt", "navy", "neal", "nebris", "need", "neeze",
    "negrine", "nelson", "neolith", "nepman", "ness", "neti", "neurad", "newing",
    "neyanda", "nibong", "niddick", "nielled", "niggard", "nimb", "ninon", "nipter",
    "nisse", "nitter", "nizy", "nock", "nodular", "noil", "nombril", "nonda",
    "nonnant", "nonwar", "noose", "norland", "nostic", "notself", "nouther", "nowise",
    "nozzle", "nucule", "nuggar", "numud", "nunnari", "nurse", "nutmeg", "nylast",
    "oaken", "oared", "oary", "oatfowl", "obclude", "obispo", "oblong", "obtect",
    "occamy", "ochone", "ocrea", "ocuby", "odds", "odist", "odyl", "offal",
    "offtake", "ogaire", "ogre", "ohoy", "oilhole", "oinomel", "oket", "oldland",
    "olena", "oliva", "olpe", "omasum", "omit", "once", "onehow", "oneyer",
    "onkos", "onrush", "onus", "oodles", "ooglea", "oologic", "ooplasm", "ootype",
    "opal", "opiism", "opsonic", "orach", "orbic", "ordain", "orenda", "orgue",
    "oriole", "ornery", "orotund", "ortet", "osazone", "oside", "osone", "ostial",
    "other", "otocyst", "ouabain", "ounce", "outback", "outing", "outrace", "ouzel",
    "ovey", "ovipara", "ower", "owly", "owtchah", "oxbird", "oxen", "oxhead",
    "oxlike", "oxtail", "oxyopia", "ozonate", "pabouch", "paco", "padre", "page",
    "pahmi", "paip", "paktong", "pall", "paly", "panfil", "panocha", "papboat",
    "papreg", "pare", "paroch", "parvenu", "past", "patible", "paty", "pausal",
    "pawer", "payable", "payroll", "pean", "pebrine", "pedder", "peed", "peeve",
    "pegwood", "peladic", "pelu", "pend", "penna", "peotomy", "peracid", "perhaps",
    "perpend", "peshkar", "pete", "petune", "pewful", "pfennig", "phanic", "phew",
    "phobiac", "phos", "phut", "piacaba", "pibroch", "picnic", "piebald", "pier",
    "pigeon", "pigroot", "pike", "pilger", "piltock", "pina", "pinhead", "pinsons",
    "pipa", "pipy", "piscary", "pist", "pitman", "piuri", "plaga", "plat",
    "pleion", "pliable", "ploat", "plough", "plug", "plyer", "pobs", "podial",
    "poesie", "pohna", "poke", "pole", "pomace", "pomster", "pony", "pooh",
    "popcorn", "poppa", "porge", "posca", "post", "potgirl", "potrack", "pouser",
    "poxy", "prairie", "pravity", "predamn", "premake", "prevail", "prig", "privacy",
    "prof", "prop", "proxeny", "pryer", "pseudo", "psykter", "ptosis", "pubian",
    "pudge", "pugged", "pukish", "puli", "pulvic", "puna", "punless", "pupoid",
    "purga", "push", "puther", "puzzle", "pygidid", "pyla", "pyre", "pyvuril",
    "quachil", "quake", "quaw", "quei", "quey", "quila", "quod", "raband",
    "rack", "radome", "ragged", "ragweed", "raioid", "rale", "ramlike", "ramular",
    "rann", "raploch", "rasgado", "rata", "ratoon", "raun", "rawness", "razz",
    "real", "reavail", "rebrace", "reclaim", "redback", "redness", "redye", "reen",
    "reflag", "regia", "rehead", "reis", "reknit", "rely", "rend", "reoccur",
    "repace", "repray", "rerig", "reskin", "rest", "retoast", "reurge", "revue",
    "reyield", "rhea", "rhetor", "rhubarb", "ribald", "rice", "ride", "rifle",
    "rignum", "rill", "rimose", "ring", "ripe", "risala", "rissel", "riva",
    "roach", "robber", "rococo", "rodless", "roer", "rohun", "roky", "romp",
    "ronyon", "roosa", "ropy", "roscid", "rosular", "roto", "rouille", "rove",
    "rowport", "rozum", "ruble", "rudas", "ruer", "rugged", "ruling", "rummage",
    "runch", "runman", "rupee", "rusine", "ruswut", "ryal", "ryot", "sabora",
    "saclike", "sadic", "safari", "sagger", "sahib", "sain", "sakulya", "salp",
    "same", "samsara", "sanicle", "sapek", "sapsago", "sari", "sarsa", "sass",
    "satura", "sauna", "savin", "sawed", "sawyer", "scab", "scap", "sceat",
    "schloop", "science", "scler", "sconce", "scrab", "scuff", "scut", "seafare",
    "sear", "sebific", "secohm", "sedent", "seeing", "seethe", "seine", "selah",
    "selt", "semsem", "sensa", "sept", "serial", "servage", "setdown", "setsman",
    "sewing", "sexless", "shaffle", "shap", "shay", "shend", "shewa", "shih",
    "shish", "shog", "shoq", "shred", "shug", "shyer", "sibbed", "sicca",
    "sidi", "siesta", "sigil", "sile", "silurid", "simlin", "sina", "sinless",
    "siol", "sircar", "siroc", "sisi", "sith", "siwash", "sizing", "skair",
    "skedge", "skeo", "skibby", "skim", "sklent", "skua", "skyish", "slab",
    "slam", "slaw", "slepez", "slifter", "slive", "sloka", "sloven", "sluice",
    "slyness", "smatter", "smeth", "smock", "smote", "smut", "snake", "sneb",
    "snib", "snivel", "snop", "snuck", "snying", "sobeit", "sock", "sodless",
    "soft", "sojourn", "solo", "somnial", "sonic", "sook", "sopite", "sore",
    "sorus", "sotol", "sough", "soutane", "sowing", "sozin", "spak", "spave",
    "spelder", "sphecid", "spike", "splash", "spoffle", "sposh", "spruce", "spur",
    "spyship", "sramana", "staia", "stases", "stead", "stela", "stey", "stile",
    "stoa", "stoke", "stosh", "stroam", "stuff", "stuss", "stypsis", "suasion",
    "subface", "subnect", "subway", "suction", "suet", "suguaro", "suit", "sull",
    "sumner", "sunk", "sunward", "surbase", "surlily", "susi", "sutler", "svelte",
    "swam", "sweal", "swidge", "swird", "swonken", "swum", "sylid", "sync",
    "syre", "syzygy", "tabog", "tacso", "tafia", "tagtail", "tahsil", "tain",
    "takin", "tald", "talthib", "tamlung", "tang", "tanoa", "taotai", "tapmost",
    "tara", "tarkhan", "tars", "task", "tatchy", "tatu", "taut", "tawn",
    "taxman", "tayra", "teacake", "team", "teaze", "tecum", "teer", "tehseel",
    "tekke", "telome", "tembe", "tenebra", "tenpin", "tepid", "terfez", "tervee",
    "tete", "teviss", "thakur", "thaught", "thegn", "these", "thig", "thiuram",
    "thole", "thread", "thujene", "thwack", "tiang", "ticca", "tide", "tier",
    "tiglic", "tikur", "tilpah", "timon", "tinhorn", "tinsel", "tiphead", "tipulid",
    "tirve", "titfish", "titter", "tjosite", "tobacco", "tocsin", "toed", "toggel",
    "toil", "told", "toman", "tomkin", "tone", "tonous", "toom", "topcap",
    "topman", "tora", "torn", "torve", "total", "totuava", "tousche", "towel",
    "towpath", "toxic", "toyon", "tradal", "trance", "treacle", "trellis", "trey",
    "trig", "trisalt", "trod", "troolie", "truancy", "trull", "tryma", "tsantsa",
    "tsun", "tubfish", "tudel", "tughra", "tuition", "tulle", "tumor", "tunful",
    "tunna", "tupuna", "turf", "turr", "tusk", "tutman", "tuxedo", "twain",
    "tweag", "twice", "twit", "tychism", "tyking", "type", "tyre", "ubiety",
    "udell", "uinal", "ulema", "ulmic", "ultra", "umbra", "unact", "unamend",
    "unaxled", "unbud", "unction", "undub", "unended", "unface", "ungag", "ungual",
    "uniat", "uninked", "univied", "unknave", "unmad", "unnoble", "unoped", "unplace",
    "unrich", "unsick", "unsued", "untrace", "unurban", "unwheel", "upaisle", "upblast",
    "upclimb", "updraft", "upfold", "upgrade", "upjerk", "upmast", "upplow", "uproad",
    "upsoak", "upthrow", "upwaft", "upyoke", "urase", "urea", "urge", "urled",
    "urnlike", "uropod", "ursuk", "usable", "usehold", "usitate", "usucapt", "utees",
    "utricle", "uvate", "uvrou", "vaalite", "vadose", "vail", "valance", "valuate",
    "vane", "vanward", "varlet", "vase", "vaudy", "vection", "veer", "vela",
    "venada", "venom", "verge", "veruled", "vessel", "veuve", "viaduct", "vibix",
    "vicuna", "vier", "vihara", "vimana", "vinic", "viqueen", "viruela", "vista",
    "viva", "voar", "void", "volt", "vorhand", "vouge", "vriddhi", "vying",
    "wacago", "wadmal", "waff", "wagtail", "wail", "waiwode", "waky", "walrus",
    "wand", "wanner", "warble", "warm", "warwolf", "wast", "wauch", "waur",
    "waxbill", "wayback", "ways", "weasand", "webster", "wedge", "ween", "weft",
    "welcome", "wemless", "were", "west", "wetted", "whar", "wheft", "whew",
    "while", "whoa", "whose", "whush", "wicht", "widish", "wifock", "wigtail",
    "will", "wimp", "winly", "wippen", "wirl", "wiss", "witjar", "wizen",
    "woan", "woevine", "wokowi", "womb", "wont", "wool", "wops", "worn",
    "woubit", "wove", "wrap", "wrest", "wrist", "wrought", "wuddie", "wungee",
    "wurzel", "wyde", "wyson", "xenon", "xyla", "xyst", "yaff", "yaje",
    "yalla", "yang", "yapok", "yarl", "yashiro", "yava", "yawy", "year",
    "yeguita", "yeni", "yern", "yeth", "yill", "yirn", "yock", "yohimbe",
    "yomer", "york", "your", "yowl", "yuck", "yurt", "zacate", "zaman",
    "zanze", "zarf", "zebra", "zeism", "zendik", "zero", "ziega", "zimarra",
    "ziphian", "zoaria", "zogan", "zonal", "zoogamy", "zootaxy", "zowie", "zygion",
];
